### ISSUE TITLE
Component

### ISSUE THREAD

**Issue by Anri-H** [fe-bootcamp-2021/your-test#5]
Vahe your work is good, in my opinion, it would be better with the input components

https://github.com/fe-bootcamp-2021/your-test/blob/4a24be20aff25f83332f2f969e5887460909dfdf/src/components/TestPopup.jsx#L11

**Comment by dav26072000** [comment]
I think so

**Comment by Vahe1209** [comment]
I am too

**Comment by dav26072000** [comment]
dzaca
